pipeline {
    agent any
    
    stages {
        stage('Checkout Codebase') {
            steps{
                checkout scm: [
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: "git@github.com:dipenkumarr/slacked.git",
                        credentialsId: "github-ssh-key"
                    ]]
                ]
            }
        }
        stage('Build') {
            steps {
                echo 'Building the project'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests on the project changes'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the project'
            }
        }
    }

    post {
        always {
            echo 'Sending Slack notification'
            sh "curl --header 'Content-Type: application/json' --request POST --data '{\"buildUrl\":\"${env.BUILD_URL}\", \"buildResult\":\"${currentBuild.result}\", \"buildNumber\":${env.BUILD_NUMBER}, \"jobName\":\"${env.JOB_NAME}\"}' https://k3xdq68f02.execute-api.us-west-2.amazonaws.com/prod/send-message"
        }
    }
}